services:
  postgres:
    image: postgres:15-alpine
    container_name: microblog_postgres
    environment:
      POSTGRES_DB: microblog
      POSTGRES_USER: microblog_user
      POSTGRES_PASSWORD: microblog_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U microblog_user -d microblog"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: microblog_app
    environment:
      DATABASE_URL: "postgres://microblog_user:microblog_password@postgres:5432/microblog?sslmode=disable"
      PORT: "8080"
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped

volumes:
  postgres_data:
