// Code generated by MockGen. DO NOT EDIT.
// Source: ../internal/ports/services/tweets_services.go
//
// Generated by this command:
//
//	mockgen -source=../internal/ports/services/tweets_services.go -destination=./mock_tweets_service.go
//

// Package mock_ports is a generated GoMock package.
package mock_ports

import (
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	domain "github.com/juanignaciorc/microbloggin-pltf/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockTweetService is a mock of TweetService interface.
type MockTweetService struct {
	ctrl     *gomock.Controller
	recorder *MockTweetServiceMockRecorder
}

// MockTweetServiceMockRecorder is the mock recorder for MockTweetService.
type MockTweetServiceMockRecorder struct {
	mock *MockTweetService
}

// NewMockTweetService creates a new mock instance.
func NewMockTweetService(ctrl *gomock.Controller) *MockTweetService {
	mock := &MockTweetService{ctrl: ctrl}
	mock.recorder = &MockTweetServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTweetService) EXPECT() *MockTweetServiceMockRecorder {
	return m.recorder
}

// CreateTweet mocks base method.
func (m *MockTweetService) CreateTweet(ctx context.Context, userID uuid.UUID, message string) (domain.Tweet, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTweet", ctx, userID, message)
	ret0, _ := ret[0].(domain.Tweet)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateTweet indicates an expected call of CreateTweet.
func (mr *MockTweetServiceMockRecorder) CreateTweet(ctx, userID, message any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTweet", reflect.TypeOf((*MockTweetService)(nil).CreateTweet), ctx, userID, message)
}
