// Code generated by MockGen. DO NOT EDIT.
// Source: ../internal/ports/repositories/tweets_repos.go
//
// Generated by this command:
//
//	mockgen -source=../internal/ports/repositories/tweets_repos.go -destination=./mock_tweets_repository.go
//

// Package mock_ports is a generated GoMock package.
package mock_ports

import (
	context "context"
	reflect "reflect"

	domain "github.com/juanignaciorc/microbloggin-pltf/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockTweetRepository is a mock of TweetRepository interface.
type MockTweetRepository struct {
	ctrl     *gomock.Controller
	recorder *MockTweetRepositoryMockRecorder
}

// MockTweetRepositoryMockRecorder is the mock recorder for MockTweetRepository.
type MockTweetRepositoryMockRecorder struct {
	mock *MockTweetRepository
}

// NewMockTweetRepository creates a new mock instance.
func NewMockTweetRepository(ctrl *gomock.Controller) *MockTweetRepository {
	mock := &MockTweetRepository{ctrl: ctrl}
	mock.recorder = &MockTweetRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTweetRepository) EXPECT() *MockTweetRepositoryMockRecorder {
	return m.recorder
}

// CreateTweet mocks base method.
func (m *MockTweetRepository) CreateTweet(ctx context.Context, tweet domain.Tweet) (domain.Tweet, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTweet", ctx, tweet)
	ret0, _ := ret[0].(domain.Tweet)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateTweet indicates an expected call of CreateTweet.
func (mr *MockTweetRepositoryMockRecorder) CreateTweet(ctx, tweet any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTweet", reflect.TypeOf((*MockTweetRepository)(nil).CreateTweet), ctx, tweet)
}
